from __future__ import annotations

from .embedding import embed_texts
from .embedding_provider import STORAGE_DIM, provider_for_embedding_model


def embed_query(q: str, dim: int = STORAGE_DIM, embedding_model: str | None = None):
    # Query embeddings must be generated by the same backend/model family as
    # the vectors stored in the target index.
    if embedding_model:
        if dim != STORAGE_DIM:
            raise ValueError(f"dim must be {STORAGE_DIM} for current storage")
        provider = provider_for_embedding_model(embedding_model)
        return provider.embed([q])[0]
    return embed_texts([q], dim=dim)[0]
